package cla.edg.project.yrzx;

import java.util.Map;

import com.terapico.changerequest.builder.ChangeRequestSpecBuilder;
import com.terapico.changerequest.builder.ChangeRequestSpecFactory;
import com.terapico.changerequest.builder.FieldType;
import com.terapico.changerequest.builder.UIStyle;

public class MainChangeRequest implements ChangeRequestSpecFactory {

	@Override
	public Map<String, Map<String, Object>> getSpec() {
		return getScript();
	}

	private Map<String, Map<String, Object>> getScript() {
		return ChangeRequestSpecBuilder.for_project("frontendpoc")
				.request_base("pocService/handleCR/")
				
				
			.change_request("show all type").zh_CN("数据类型展示")
				.icon("table")
				.has_field("field_text").zh_CN("短文本").which_type_of(FieldType.TEXT).with_style(UIStyle.INPUT_TEXT)
				.has_field("field_id_number").zh_CN("身份证").which_type_of(FieldType.TEXT)
					.range(15,18)
				.has_field("field_email").zh_CN("电子邮件").with_style(UIStyle.INPUT_EMAIL)
					.match("^(\\w)+(\\.\\w+)*@(\\w)+((\\.\\w+)+)$")
				.has_field("field_url").zh_CN("链接").with_style(UIStyle.INPUT_URL)
				.has_field("field_one_of").zh_CN("单选")
					.values_canbe("sport", "运动").or("sleep", "睡觉")
				.has_field("field_some_of").zh_CN("多选")
					.values_canbe("sport", "运动").and("reading", "阅读").and("music", "音乐").and("movie", "电影").and("game", "游戏")
				.has_field("field_longtext").zh_CN("长文本").which_type_of(FieldType.MULTI_TEXT)
				.has_field("field_boolean").zh_CN("布尔").which_type_of(FieldType.BOOLEAN)
				.has_field("field_images").zh_CN("多图").which_type_of(FieldType.IMAGES)
				.has_field("field_image").zh_CN("单图").which_type_of(FieldType.IMAGE)
				.has_field("field_date").zh_CN("日期").which_type_of(FieldType.DATE)
				.has_field("field_datetime").zh_CN("日期时间").which_type_of(FieldType.DATE_TIME)
				.has_field("field_time").zh_CN("时间").which_type_of(FieldType.TIME).with_style(UIStyle.INPUT_TEXT)
				.has_field("field_integer").zh_CN("整数").which_type_of(FieldType.INTEGER)
				.has_field("field_decimal").zh_CN("小数").which_type_of(FieldType.DECIMAL)
				.has_field("field_money").zh_CN("金融").which_type_of(FieldType.MONEY).range(100,10000)
				
			.change_request("task daily report").zh_CN("施工日志")
				.icon("calendar")
				.step("basic info").zh_CN("基本信息")
					.contains_event("task report basic info").zh_CN("施工基础信息")
						.has_field("task id").zh_CN("工程").hidden().defaule_value("T000001")
						.has_field("task_name").zh_CN("工程名称")
							.disabled()
							.defaule_value("XXX施工")
							.range(1,100)
							.sample_data("墙面施工|水电改造|隔离层鼓包二次整改")
						.has_field("subcontractor_name").zh_CN("分包单位")
							.disabled()
							.defaule_value("XXX建筑公司")
							.range(1,100)
							.sample_data("四川闫明建筑公司|活力装修设计工作室")
						.has_field("responsible_name").zh_CN("施工负责人")
							.disabled()
							.defaule_value("工人XXX")
							.range(1,100)
							.sample_data("张黎明|李大力")
						.has_field("temperature").zh_CN("气温")
							.which_type_of(FieldType.DECIMAL)
							.range(-273.00, 5000)
							.place_holder("请填写施工现场温度")
							.sample_data("17.66|25.01")
						.has_field("weather conditions").zh_CN("天气情况")
							.place_holder("请选择天气情况")
							.values_canbe("晴", "晴").or("阴", "阴").or("雨", "雨")
				.step("step 2").zh_CN("施工质量、安全、进度、机械、劳动力状况及需求")
					.contains_event("common report").zh_CN("日报内容").as("content")
						.has_field("content").zh_CN("描述").which_type_of(FieldType.MULTI_TEXT)
							.optional()
							.place_holder("请输入报告的内容")
						.has_field("images").zh_CN("现场照片").which_type_of(FieldType.IMAGES)
							.optional()
							.place_holder("请上传照片")
//						.has_field("attachment").zh_CN("相关资料").which_type_of(FieldType.)
				.step("step 3").zh_CN("进场材料、使用、检验、封样")
					.contains_event("common report").zh_CN("进场材料、使用、检验、封样")
				.step("step 4").zh_CN("存在安全、质量问题处理意见")
					.contains_event("common report").zh_CN("存在安全、质量问题处理意见")
				.step("step 5").zh_CN("文明施工情况及处理办法见")
					.contains_event("common report").zh_CN("文明施工情况及处理办法")
				.step("step 6").zh_CN("施工配合情况")
					.contains_event("common report").zh_CN("施工配合情况")
					
			.change_request("project manager daily report").zh_CN("项目经理日志")
				.icon("tachometer")
				.step("basic info").zh_CN("基本信息")
					.contains_event("project manager report basic info").zh_CN("施工基础信息")
						.has_field("project id").zh_CN("项目").hidden().defaule_value("P000001")
						.has_field("project_name").zh_CN("工程名称")
							.disabled()
							.defaule_value("XXX装修")
							.range(1,100)
							.sample_data("火车北站候车室装修工程|三峡大坝装修工程")
						.has_field("temperature").zh_CN("气温")
							.which_type_of(FieldType.DECIMAL)
							.range(-273.00, 5000)
							.place_holder("请填写施工现场温度")
							.sample_data("17.66|25.01")
						.has_field("weather conditions").zh_CN("天气情况")
							.place_holder("请选择天气情况")
							.values_canbe("晴", "晴").or("阴", "阴").or("雨", "雨")
				.step("step 2").zh_CN("当日情况总结")
					.contains_event("common report").zh_CN("当日情况总结").as("content")
				.step("step 3").zh_CN("当日情况检查单")
					.contains_event("report check item").zh_CN("检查项").as("project hidden trouble").zh_CN("项目隐患")
						.has_field("check result").zh_CN("检查结果")
							.values_canbe("有", "有").or("无", "无")
							.place_holder("请选择")
						.has_field("process result").zh_CN("处理结果")
							.values_canbe("resolved", "已解决").or("not_resolved", "未解决")
							.place_holder("是否已处理")
							.defaule_value("not_resolved")
					.contains_event("report check item").as("work quanlity").zh_CN("施工质量")
						.for_field("check result").values_canbe("正常", "正常").or("不正常", "不正常")
					.contains_event("report check item").as("patrol").zh_CN("旁站/见证/巡视")
						.for_field("check result").values_canbe("有", "有").or("无", "无")
					.contains_event("report check item").as("acceptance").zh_CN("验收签证")
						.for_field("check result").values_canbe("有", "有").or("无", "无")
					.contains_event("report check item").as("safty").zh_CN("安全文明施工")
						.for_field("check result").values_canbe("有", "有").or("无", "无")
					.contains_event("report check item").as("progress").zh_CN("施工进度")
						.for_field("check result").values_canbe("正常", "正常").or("不正常", "不正常")
					.contains_event("report check item").as("materials").zh_CN("材料管理")
						.for_field("check result").values_canbe("正常", "正常").or("不正常", "不正常")
					.contains_event("report check item").as("subcontract execution").zh_CN("分包合同执行")
						.for_field("check result").values_canbe("正常", "正常").or("不正常", "不正常")
					.contains_event("report check item").as("field meeting").zh_CN("现场会议与发文")
						.for_field("check result").values_canbe("有", "有").or("无", "无")
					.contains_event("report check item").as("over time").zh_CN("有无加班")
						.for_field("check result").values_canbe("有", "有").or("无", "无")
					.contains_event("report check item").as("organization").zh_CN("人员组织状态")
						.for_field("check result").values_canbe("正常", "正常").or("不正常", "不正常")
					.contains_event("report check item").as("summary").zh_CN("当日整体评价及结果")
						.for_field("check result").values_canbe("正常", "正常").or("不正常", "不正常")
			.getChangeRequestSpec();
	}
}
